// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0ue_rxVL12nU5B995Gb6wCGqXVS0BB0',
    appId: '1:995192202329:android:1970f1731d25d16aae7d48',
    messagingSenderId: '995192202329',
    projectId: 'invernadero-iot-dfa2f',
    storageBucket: 'invernadero-iot-dfa2f.firebasestorage.app',
    databaseURL: 'https://invernadero-iot-dfa2f-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjXaULyZVVv3G0d3TuRBiYyxjpysrDPxQ',
    appId: '1:995192202329:ios:f109fb62a471dae2ae7d48',
    messagingSenderId: '995192202329',
    projectId: 'invernadero-iot-dfa2f',
    storageBucket: 'invernadero-iot-dfa2f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
    databaseURL: 'https://invernadero-iot-dfa2f-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxOnftkID-gjD6kUPwJLn_k1wrwT0Gs4',
    appId: '1:995192202329:web:7b6611c8975e0966ae7d48',
    messagingSenderId: '995192202329',
    projectId: 'invernadero-iot-dfa2f',
    authDomain: 'invernadero-iot-dfa2f.firebaseapp.com',
    storageBucket: 'invernadero-iot-dfa2f.firebasestorage.app',
    measurementId: 'G-B09XX0PM33',
    databaseURL: 'https://invernadero-iot-dfa2f-default-rtdb.firebaseio.com',
  );

}